### PR TITLE
Fix more -Wunused-but-set-variable warnings.

### LINKED ISSUE #469: more -Wunused-but-set-variable warnings
The following shows up in CI emscripten build jobs:
```
src/loaders/st_load.c:211:6: warning: variable 'smp_size' set but not used [-Wunused-but-set-variable]
        int smp_size;
            ^

src/loaders/ims_load.c:150:9: warning: variable 'smp_size' set but not used [-Wunused-but-set-variable]
    int smp_size;
        ^

src/loaders/prowizard/p61a.c:36:9: warning: variable 'ssize' set but not used [-Wunused-but-set-variable]
    int ssize = 0;
        ^
src/loaders/prowizard/p61a.c:566:9: warning: variable 'ssize' set but not used [-Wunused-but-set-variable]
    int ssize;
        ^

src/mix_paula.c:133:1: warning: parameter 'vr' set but not used [-Wunused-but-set-parameter]
MIXER(mono_a500)
^
src/mixer.h:18:25: note: expanded from macro 'MIXER'
        int count, int vl, int vr, int step, int ramp, int delta_l, int delta_r)
                               ^
src/mix_paula.c:140:1: warning: parameter 'vr' set but not used [-Wunused-but-set-parameter]
MIXER(mono_a500_filter)
^
src/mixer.h:18:25: note: expanded from macro 'MIXER'
        int count, int vl, int vr, int step, int ramp, int delta_l, int delta_r)
                               ^

src/depackers/uncompress.c:74:7: warning: variable 'bytes_in' set but not used [-Wunused-but-set-variable]
        long bytes_in;                  /* Total number of byte from input */
             ^
```

### PR DESCRIPTION
**Pull request by AliceLR**
Fixes #469. Commit 1 fixes everything but the -Wclobbered in bunzip2.c and commit 2 just fixes the -Wclobbered. I haven't verified this actually works yet since the warning doesn't happen locally for me.

edit: there are two more I missed...

### CODE REVIEW

File: src/depackers/bunzip2.c [hunk 1]
```diff
@@ -132,7 +132,7 @@ static int get_next_block(bunzip_data *bd)
 	unsigned char uc, symToByte[256], mtfSymbol[256], *selectors;
 	unsigned int *dbuf,origPtr;
 
-	hufGroup=NULL;
+	hufGroup=bd->groups; /* silence -Wclobbered */
```
Comment (sezero) [inline src/depackers/bunzip2.c:135]: This doesn't help. I thought of moving setjmp before the local var assignments.

File: src/mix_paula.c [hunk 2]
```diff
@@ -125,21 +125,25 @@ static void do_clock(struct paula_state *paula, int cycles)
     unsigned int pos = vi->pos; \
     int frac = (1 << SMIX_SHIFT) * (vi->pos - (int)vi->pos)
 
+#define VAR_PAULA_MONO(x) \
+    VAR_NORM(x); \
+    vl <<= 8
+
```
Comment (sezero) [inline src/mix_paula.c:131]: Don't touch it, and no warnings  -  huh..

File: src/depackers/bunzip2.c (hunk 1 above)
Comment (sezero) [reply src/depackers/bunzip2.c:135]: The rest are OK

File: src/mix_paula.c (hunk 2 above)
Comment (AliceLR) [reply src/mix_paula.c:131]: Right, because `-Wno-unused-parameter` is used. For some reason the second you touch it, it triggers a *completely different* warning...

File: src/depackers/bunzip2.c (hunk 1 above)
Comment (AliceLR) [reply src/depackers/bunzip2.c:135]: Which CI run was emitting this particular warning? Was it Ubuntu 16.04?

Comment (sezero) [reply src/depackers/bunzip2.c:135]: My local run - I see it with gcc4.9 and gcc2.95

Comment (sezero) [reply src/depackers/bunzip2.c:135]: Is the following wrong?
```diff
diff --git a/src/depackers/bunzip2.c b/src/depackers/bunzip2.c
index 8a8a874..83fe918 100644
--- a/src/depackers/bunzip2.c
+++ b/src/depackers/bunzip2.c
@@ -132,13 +132,15 @@ static int get_next_block(bunzip_data *bd)
 	unsigned char uc, symToByte[256], mtfSymbol[256], *selectors;
 	unsigned int *dbuf,origPtr;
 
+	/* Reset longjmp I/O error handling */
+	i=setjmp(bd->jmpbuf);
+	if(i) return i;
+
 	hufGroup=NULL;
 	dbuf=bd->dbuf;
 	dbufSize=bd->dbufSize;
 	selectors=bd->selectors;
-	/* Reset longjmp I/O error handling */
-	i=setjmp(bd->jmpbuf);
-	if(i) return i;
+
 	/* Read in header signature and CRC, then validate signature.
 	   (last block signature means CRC is for whole file, return now) */
 	i = get_bits(bd,24);
```

Comment (AliceLR) [reply src/depackers/bunzip2.c:135]: > My local run - I see it with gcc4.9 and gcc2.95

Weird—I just did builds with gcc 4.8.5 (CentOS 7) and 4.1.2 (Debian 4.0 SPARC) and neither came up with that warning. I definitely saw it with the Ubuntu 16.04 workflow, though...

That patch looks OK to me. If it fixes the warning on your end I'll go ahead and switch to your fix.

**Review by sezero — APPROVED** [review]
