### PR TITLE
Fix ProWizard bugs found by fuzzing (batch 7) and add loader tests.

### LINKED ISSUE #277: Several Pha Packer test modules fail to load.
Split from the comments of #266—several of the PHA ProPacker test files linked in the comments for that PR do not load. Whatever the issue is, I was able to reproduce it building from a commit from several years ago, so it's not a new bug.

[ProPacker examples (PHA).zip](https://github.com/libxmp/libxmp/files/5773084/ProPacker.examples.PHA.zip)

### LINKED ISSUE #280: Memory errors revealed by AFL++, batch 7
With HEAD at dbcb4d5ee9278256658f663c286025e55a10c3e0 + a manual application of the patch from #279 as it stands at the time of this writing, about half of the unique issues which were still showing up in my previous build have disappeared, and the size of the tarball of remaining crash-inducing samples has been cut by more than two thirds :)
However, I can still see 8 different stack traces, 2-3 of which appeared in the past 3 days. 3 of these seem to occur outside Prowizard loader files, which probably warrants a new issue.

```
Loading output/1/crashes/id:000135,sig:06,src:004753,time:6028808,op:havoc,rep:8 (1 of 1)
=================================================================
==257070==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000410 at pc 0x7ffb337e7f45 bp 0x7ffd3672e590 sp 0x7ffd3672e588
READ of size 4 at 0x602000000410 thread T0
    #0 0x7ffb337e7f44 in depack_p10c .../xmp/libxmp/src/loaders/prowizard/pm10c.c:180:5
    #1 0x7ffb337c9d63 in pw_wizardry .../xmp/libxmp/src/loaders/prowizard/prowiz.c:112:6
    #2 0x7ffb337b5f69 in pw_load .../xmp/libxmp/src/loaders/pw_load.c:81:6
    #3 0x7ffb33703540 in load_module .../xmp/libxmp/src/load.c:461:18
    #4 0x7ffb337028ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #5 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #6 0x7ffb3321bd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #7 0x420679 in _start (.../bin/xmp+0x420679)

Address 0x602000000410 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow .../xmp/libxmp/src/loaders/prowizard/pm10c.c:180:5 in depack_p10c
```

```
Loading output/1/crashes/id:000512,sig:06,src:017168+012614,time:442942140,op:splice,rep:4 (1 of 1)
=================================================================
==260936==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc796d9b60 at pc 0x7febe96533b7 bp 0x7ffc796d9410 sp 0x7ffc796d9408
WRITE of size 4 at 0x7ffc796d9b60 thread T0
    #0 0x7febe96533b6 in depack_tp1 .../xmp/libxmp/src/loaders/prowizard/tp1.c:61:12
    #1 0x7febe9626d63 in pw_wizardry .../xmp/libxmp/src/loaders/prowizard/prowiz.c:112:6
    #2 0x7febe9612f69 in pw_load .../xmp/libxmp/src/loaders/pw_load.c:81:6
    #3 0x7febe9560540 in load_module .../xmp/libxmp/src/load.c:461:18
    #4 0x7febe955f8ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #5 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #6 0x7febe9078d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #7 0x420679 in _start (.../bin/xmp+0x420679)

Address 0x7ffc796d9b60 is located in stack of thread T0 at offset 1856 in frame
    #0 0x7febe965302f in depack_tp1 .../xmp/libxmp/src/loaders/prowizard/tp1.c:14

  This frame has 4 object(s):
    [32, 160) 'pnum' (line 16)
    [192, 1216) 'pdata' (line 17)
    [1344, 1856) 'paddr' (line 23) <== Memory access at offset 1856 overflows this variable
    [1920, 2432) 'paddr_ord' (line 24)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow .../xmp/libxmp/src/loaders/prowizard/tp1.c:61:12 in depack_tp1
```

```
Loading output/1/crashes/id:000562,sig:06,src:017662,time:840812370,op:havoc,rep:4 (1 of 1)
=================================================================
==261608==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000001810 at pc 0x7f79e3f73d9d bp 0x7ffeac2fc6b0 sp 0x7ffeac2fc6a8
READ of size 4 at 0x602000001810 thread T0
    #0 0x7f79e3f73d9c in depack_p18a .../xmp/libxmp/src/loaders/prowizard/pm18a.c:132:5
    #1 0x7f79e3f53d63 in pw_wizardry .../xmp/libxmp/src/loaders/prowizard/prowiz.c:112:6
    #2 0x7f79e3f3ff69 in pw_load .../xmp/libxmp/src/loaders/pw_load.c:81:6
    #3 0x7f79e3e8d540 in load_module .../xmp/libxmp/src/load.c:461:18
    #4 0x7f79e3e8c8ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #5 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #6 0x7f79e39a5d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #7 0x420679 in _start (.../bin/xmp+0x420679)

Address 0x602000001810 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow .../xmp/libxmp/src/loaders/prowizard/pm18a.c:132:5 in depack_p18a
```

```
Loading output/1/crashes/id:000652,sig:06,src:017394,time:1289772803,op:havoc,rep:8 (1 of 1)
=================================================================
==263721==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60d0000000c2 at pc 0x7f8054624694 bp 0x7fff0068bf00 sp 0x7fff0068bef8
READ of size 1 at 0x60d0000000c2 thread T0
    #0 0x7f8054624693 in readmem24b .../xmp/libxmp/src/dataio.c:196:6
    #1 0x7f80547591d0 in get_bits_final .../xmp/libxmp/src/depackers/unsqsh.c:75:10
    #2 0x7f80547591d0 in unsqsh_block .../xmp/libxmp/src/depackers/unsqsh.c:217:12
    #3 0x7f80547591d0 in unsqsh .../xmp/libxmp/src/depackers/unsqsh.c:316:7
    #4 0x7f80547591d0 in decrunch_sqsh .../xmp/libxmp/src/depackers/unsqsh.c:362:6
    #5 0x7f805464a7be in decrunch .../xmp/libxmp/src/load.c:221:7
    #6 0x7f805464b54f in xmp_load_module .../xmp/libxmp/src/load.c:571:6
    #7 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #8 0x7f8054164d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #9 0x420679 in _start (.../bin/xmp+0x420679)

0x60d0000000c2 is located 0 bytes to the right of 130-byte region [0x60d000000040,0x60d0000000c2)
allocated by thread T0 here:
    #0 0x49a6ed in malloc (.../bin/xmp+0x49a6ed)
    #1 0x7f805475851d in decrunch_sqsh .../xmp/libxmp/src/depackers/unsqsh.c:353:13
    #2 0x7f805464a7be in decrunch .../xmp/libxmp/src/load.c:221:7
    #3 0x7f805464b54f in xmp_load_module .../xmp/libxmp/src/load.c:571:6
    #4 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #5 0x7f8054164d09 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow .../xmp/libxmp/src/dataio.c:196:6 in readmem24b
```

```
Loading output/1/crashes/id:000699,sig:06,src:018446,time:1952587791,op:havoc,rep:2 (1 of 1)
=================================================================
==264309==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d000000878 at pc 0x00000043850e bp 0x7ffcf7178670 sp 0x7ffcf7177e38
WRITE of size 4 at 0x61d000000878 thread T0
    #0 0x43850d in fread (.../bin/xmp+0x43850d)
    #1 0x7f08d0371223 in hio_read .../xmp/libxmp/src/hio.c:232:9
    #2 0x7f08d03eaa6d in subchunk_oplh .../xmp/libxmp/src/loaders/masi_load.c:542:4
    #3 0x7f08d03eaa6d in get_song_2 .../xmp/libxmp/src/loaders/masi_load.c:692:8
    #4 0x7f08d037cb2a in iff_process .../xmp/libxmp/src/loaders/iff.c:55:8
    #5 0x7f08d037cb2a in iff_chunk .../xmp/libxmp/src/loaders/iff.c:127:9
    #6 0x7f08d037cb2a in libxmp_iff_load .../xmp/libxmp/src/loaders/iff.c:151:9
    #7 0x7f08d03e9e51 in masi_load .../xmp/libxmp/src/loaders/masi_load.c:800:6
    #8 0x7f08d036e540 in load_module .../xmp/libxmp/src/load.c:461:18
    #9 0x7f08d036d8ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #10 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #11 0x7f08cfe86d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #12 0x420679 in _start (.../bin/xmp+0x420679)

0x61d000000878 is located 0 bytes to the right of 2040-byte region [0x61d000000080,0x61d000000878)
allocated by thread T0 here:
    #0 0x49a6ed in malloc (.../bin/xmp+0x49a6ed)
    #1 0x7f08d03e9c3c in masi_load .../xmp/libxmp/src/loaders/masi_load.c:761:14
    #2 0x7f08d036e540 in load_module .../xmp/libxmp/src/load.c:461:18
    #3 0x7f08d036d8ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #4 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #5 0x7f08cfe86d09 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow (.../bin/xmp+0x43850d) in fread
```

```
Loading output/1/crashes/id:000748,sig:06,src:003655,time:2589055178,op:havoc,rep:4 (1 of 1)
=================================================================
==265136==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc2bbdfe04 at pc 0x7f967b6533cc bp 0x7ffc2bbdfb70 sp 0x7ffc2bbdfb68
READ of size 2 at 0x7ffc2bbdfe04 thread T0
    #0 0x7f967b6533cb in st_test .../xmp/libxmp/src/loaders/st_load.c:192:24
    #1 0x7f967b5f049c in load_module .../xmp/libxmp/src/load.c:457:17
    #2 0x7f967b5ef8ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #3 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #4 0x7f967b108d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #5 0x420679 in _start (.../bin/xmp+0x420679)

Address 0x7ffc2bbdfe04 is located in stack of thread T0 at offset 644 in frame
    #0 0x7f967b651fbf in st_test .../xmp/libxmp/src/loaders/st_load.c:49

  This frame has 2 object(s):
    [32, 632) 'mh' (line 52) <== Memory access at offset 644 overflows this variable
    [768, 772) 'mod_event' (line 53)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow .../xmp/libxmp/src/loaders/st_load.c:192:24 in st_test
```

```
=================================================================
==265493==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe16485ce0 at pc 0x7f3f8f2b23b8 bp 0x7ffe16484f90 sp 0x7ffe16484f88
WRITE of size 4 at 0x7ffe16485ce0 thread T0
    #0 0x7f3f8f2b23b7 in depack_np3 .../xmp/libxmp/src/loaders/prowizard/np3.c:84:23
    #1 0x7f3f8f29ad63 in pw_wizardry .../xmp/libxmp/src/loaders/prowizard/prowiz.c:112:6
    #2 0x7f3f8f286f69 in pw_load .../xmp/libxmp/src/loaders/pw_load.c:81:6
    #3 0x7f3f8f1d4540 in load_module .../xmp/libxmp/src/load.c:461:18
    #4 0x7f3f8f1d38ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #5 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #6 0x7f3f8ececd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #7 0x420679 in _start (.../bin/xmp+0x420679)

Address 0x7ffe16485ce0 is located in stack of thread T0 at offset 3392 in frame
    #0 0x7f3f8f2b17df in depack_np3 .../xmp/libxmp/src/loaders/prowizard/np3.c:18

  This frame has 3 object(s):
    [32, 1056) 'tmp' (line 19)
    [1184, 1312) 'ptable' (line 21)
    [1344, 3392) 'trk_addr' (line 26) <== Memory access at offset 3392 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow .../xmp/libxmp/src/loaders/prowizard/np3.c:84:23 in depack_np3
```

```
Loading output/2/crashes/id:000488,sig:06,src:000832+014280,time:245672398,op:splice,rep:4 (1 of 1)
=================================================================
==272948==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x626000002d00 at pc 0x7f952b8dd5c6 bp 0x7ffebb1d6190 sp 0x7ffebb1d6188
READ of size 1 at 0x626000002d00 thread T0
    #0 0x7f952b8dd5c5 in depack_pha .../xmp/libxmp/src/loaders/prowizard/pha.c:234:9
    #1 0x7f952b8bad63 in pw_wizardry .../xmp/libxmp/src/loaders/prowizard/prowiz.c:112:6
    #2 0x7f952b8a6f69 in pw_load .../xmp/libxmp/src/loaders/pw_load.c:81:6
    #3 0x7f952b7f4540 in load_module .../xmp/libxmp/src/load.c:461:18
    #4 0x7f952b7f38ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #5 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #6 0x7f952b30cd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #7 0x420679 in _start (.../bin/xmp+0x420679)

0x626000002d00 is located 0 bytes to the right of 11264-byte region [0x626000000100,0x626000002d00)
allocated by thread T0 here:
    #0 0x49a6ed in malloc (.../bin/xmp+0x49a6ed)
    #1 0x7f952b8dca79 in depack_pha .../xmp/libxmp/src/loaders/prowizard/pha.c:199:20
    #2 0x7f952b8bad63 in pw_wizardry .../xmp/libxmp/src/loaders/prowizard/prowiz.c:112:6
    #3 0x7f952b7f4540 in load_module .../xmp/libxmp/src/load.c:461:18
    #4 0x7f952b7f38ac in xmp_load_module .../xmp/libxmp/src/load.c:609:8
    #5 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #6 0x7f952b30cd09 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow .../xmp/libxmp/src/loaders/prowizard/pha.c:234:9 in depack_pha
```

This tarball contains multiple samples for most issues:
[remaining_crashes_20210106_1124.tar.gz](https://github.com/libxmp/libxmp/files/5775394/remaining_crashes_20210106_1124.tar.gz)

### PR DESCRIPTION
**Pull request by AliceLR**
This fixes all of the ProWizard crash bugs found in #280 and also the non-crash bug #277:

* Out-of-bounds reads in the Promizer 1.0c and 1.8a loaders caused by not validating note references.
* Stack corruption in the Tracker Packer 1 loader caused by a faulty song length check in the test function.
* Stack corruption in the NoisePacker 3 loader caused by an off-by-one sanity check in the test function.
* Out-of-bounds reads in the Pha Packer loader caused by missing sanity checks.
* Valid Pha Packer modules would fail to load due to the EOF state not getting cleared. This loader relies on reading to the end of the file to get pattern data, followed by a seek back to the sample data. fseek would have cleared the EOF flag, but apparently hio_seek does not clear this. I just added an hio_error call to patch this.

Also adds loader tests for the FC-M Packer, Game Music Creator, Novotrade Packer, Tracker Packer 1 & 2, and Pha Packer formats. I'm reasonably sure these files are being loaded mostly correctly but they all have slight differences from their MOD versions (when available).

With this patch, all of the fuzzing files I currently have from @debrouxl's fuzzing efforts no longer cause crashes with ASan.

Fixes #277. Fixes #280.

### CODE REVIEW

File: src/loaders/prowizard/tp1.c [hunk 1]
```diff
@@ -193,7 +193,7 @@ static int test_tp1(const uint8 *data, char *t, int s)
 	}
 
 	/* pattern list size */
-	len = data[281];
+	len = readmem16b(data + 280) + 1;
 	if (len == 0 || len > 128) {
```
Comment (sezero) [inline src/loaders/prowizard/tp1.c:197]: The `len == 0` check here is stale now, isn't it?

**Comment by debrouxl** [comment]
Unsurprisingly, my test result match yours: no more crashes on my side either, even with an additional day of fuzzing which let the number of execs surpass 3G. Good work :)

I'll let you modify / relax the checks a bit to fix issues 284 to 288, at your leisure, and I guess I'll start at least one new instance of afl-fuzz on the fixed binary and the new test suite.

File: src/loaders/prowizard/tp1.c (hunk 1 above)
Comment (AliceLR) [reply src/loaders/prowizard/tp1.c:197]: Not only is it stale but, since 0 seems to mean 1 position in the order list, it probably was never correct.

**Review by sezero — APPROVED** [review]
